import { execFileSync, spawn, spawnSync, type ChildProcess } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const PORT = 8000;

async function waitForHealth(timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      if ((await fetch(`http://127.0.0.1:${PORT}/api/v1/health`)).ok) return;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error("Test backend did not become healthy.");
}

/**
 * Starts a throwaway backend and a disposable Git repository entirely under the OS temp directory.
 * The API token is generated by the backend into that directory; it is passed to tests through the
 * environment and is never written into the repository or printed.
 */
export default async function globalSetup(): Promise<() => Promise<void>> {
  try {
    await fetch(`http://127.0.0.1:${PORT}/api/v1/health`);
    throw new Error(`Port ${PORT} is already in use. Stop the running backend before running e2e tests.`);
  } catch (error) {
    if ((error as Error).message.startsWith("Port")) throw error;
  }

  const work = mkdtempSync(join(tmpdir(), "ca-e2e-"));
  const dbDir = join(work, "db");
  const repo = join(work, "repo with spaces");
  mkdirSync(dbDir);
  mkdirSync(repo);

  const git = (...args: string[]) => execFileSync("git", args, { cwd: repo, stdio: "ignore" });
  git("init", "-q");
  git("config", "user.email", "e2e@example.invalid");
  git("config", "user.name", "E2E");
  writeFileSync(join(repo, "README.md"), "# throwaway\n");
  git("add", ".");
  git("commit", "-q", "-m", "init");

  const child: ChildProcess = spawn(
    process.env.CHANGE_ASSURANCE_PYTHON || "python",
    ["-s", "-m", "uvicorn", "backend.app.main:app", "--host", "127.0.0.1", "--port", String(PORT)],
    {
      cwd: repoRoot,
      shell: false,
      windowsHide: true,
      stdio: "ignore",
      env: { ...process.env, CHANGE_ASSURANCE_DB_PATH: join(dbDir, "ca.sqlite3"), CHANGE_ASSURANCE_API_TOKEN: "" },
    },
  );
  await waitForHealth(30_000);

  process.env.CA_E2E_TOKEN = readFileSync(join(dbDir, "api_token"), "utf8").trim();
  process.env.CA_E2E_REPO = repo;

  return async () => {
    // Kill the whole tree: on Windows `python` may be a launcher shim whose child is the real interpreter.
    if (child.pid) spawnSync("taskkill", ["/PID", String(child.pid), "/T", "/F"], { stdio: "ignore" });
    else child.kill();
    await new Promise((r) => setTimeout(r, 500));
  };
}
