"""Map the changed lines of a checkpoint-bound Python diff."""

from __future__ import annotations

import codecs
import re
from dataclasses import dataclass, field
from pathlib import Path

from backend.app.contracts.models import GitCheckpoint
from backend.app.core.errors import AppError
from backend.app.git.safe_exec import run_git

_HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(?:.*)$")


@dataclass(slots=True)
class DiffMap:
    lines: dict[str, set[int]] = field(default_factory=dict)
    excluded: dict[str, str] = field(default_factory=dict)
    error: str | None = None


def _classification(path: str, root: Path | None = None) -> str | None:
    lower = "/" + path.lower().replace("\\", "/")
    name = lower.rsplit("/", 1)[-1]
    if ("/tests/" in lower or "/test/" in lower or name == "conftest.py"
            or (name.startswith("test_") and name.endswith(".py"))
            or name.endswith("_test.py")):
        return "test code"
    if lower.endswith((".toml", ".yaml", ".yml", ".json", ".ini", ".cfg")):
        return "configuration"
    if lower.endswith((".md", ".rst", ".txt")):
        return "documentation"
    if not lower.endswith(".py"):
        if lower.endswith((".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
                           ".java", ".go", ".rs", ".cs", ".rb")):
            return "unsupported language"
        return "non-source file"
    if root is not None:
        source = root / path
        try:
            if source.is_file() and not source.is_symlink():
                with source.open("rb") as stream:
                    first_lines = stream.read(4096).decode("utf-8").splitlines()[:5]
                if any(line.lstrip().lower().startswith(("# generated by ",
                                                          "# auto-generated", "# autogenerated"))
                       for line in first_lines):
                    return "generated"
        except (OSError, UnicodeError):
            pass
    return None


def _destination_path(raw: str) -> str | None:
    """Decode Git's optional C-quoted path and remove its destination prefix."""

    raw = raw.removesuffix("\t")
    if raw == "/dev/null":
        return None
    if raw.startswith('"') and raw.endswith('"'):
        try:
            raw = codecs.escape_decode(raw[1:-1].encode("utf-8"))[0].decode("utf-8")
        except (UnicodeError, ValueError):
            raise ValueError("Git destination path is not valid UTF-8") from None
    if not raw.startswith("b/") or any(mark in raw for mark in ("\0", "\n", "\r", "\t")):
        raise ValueError("Git destination path is unsafe or has an unexpected prefix")
    return raw[2:]


def _parse_patch(patch: str, result: DiffMap, root: Path | None = None) -> None:
    """Consume Git's patch grammar; source lines are never trusted as headers."""

    path: str | None = None
    in_file = saw_old = saw_new = False
    old_left = new_left = 0
    old_no = new_no = 0
    classifications: dict[str, str | None] = {}
    records = patch.split("\n")
    for index, raw in enumerate(records):
        line = raw[:-1] if raw.endswith("\r") else raw
        if not line and index == len(records) - 1:
            continue
        if line.startswith("\\ No newline at end of file"):
            continue
        if old_left or new_left:
            marker = line[:1]
            if marker == "+" and new_left:
                if path is not None:
                    if path not in classifications:
                        classifications[path] = _classification(path, root)
                    classification = classifications[path]
                    if classification:
                        result.excluded[path] = classification
                    else:
                        result.lines.setdefault(path, set()).add(new_no)
                new_no += 1
                new_left -= 1
            elif marker == "-" and old_left:
                old_no += 1
                old_left -= 1
            elif marker == " " and old_left and new_left:
                old_no += 1
                new_no += 1
                old_left -= 1
                new_left -= 1
            else:
                result.error = "Diff hunk body did not reconcile with its header."
                return
            continue
        if line.startswith("diff --git "):
            in_file, saw_old, saw_new = True, False, False
            path = None
        elif line.startswith("--- ") and in_file and not saw_old:
            saw_old = True
        elif line.startswith("+++ ") and in_file and saw_old and not saw_new:
            saw_new = True
            try:
                path = _destination_path(line[4:])
            except ValueError as exc:
                result.error = str(exc)
                return
        elif line.startswith("@@"):
            match = _HUNK.match(line)
            if match is None or not saw_new:
                result.error = "Malformed zero-context diff hunk."
                return
            old_no = int(match.group(1))
            old_left = int(match.group(2) or "1")
            new_no = int(match.group(3))
            new_left = int(match.group(4) or "1")
            if path is None and new_left:
                result.error = "Deletion hunk unexpectedly adds lines."
                return
        elif line.startswith("Binary files ") and line.endswith(" differ"):
            pair = line[len("Binary files "):-len(" differ")].rsplit(" and ", 1)
            if len(pair) != 2:
                result.error = "Binary diff path could not be identified."
                return
            try:
                binary_path = _destination_path(pair[1])
            except ValueError:
                result.error = "Binary diff path could not be identified."
                return
            if binary_path is None or binary_path.lower().endswith(".py"):
                result.error = "Binary Python source cannot be mapped."
                return
            result.excluded[binary_path] = "binary"
        elif line.startswith("GIT binary patch"):
            result.error = "Binary patch cannot be mapped."
            return
        elif line and not line.startswith(("index ", "new file mode ", "deleted file mode ",
                                           "old mode ", "new mode ", "similarity index ",
                                           "dissimilarity index ", "rename from ", "rename to ",
                                           "copy from ", "copy to ", "a/", "b/")):
            result.error = "Unexpected diff record."
            return
    if old_left or new_left:
        result.error = "Diff ended before its hunk body was complete."


def map_diff(*, baseline: GitCheckpoint, tested: GitCheckpoint, limit: int = 8_388_608) -> DiffMap:
    """Use the baseline commit and current worktree; refuse un-reconstructable baselines."""

    result = DiffMap()
    if baseline.repository_root != tested.repository_root or baseline.change_id != tested.change_id:
        result.error = "Checkpoints belong to different repositories or Changes."
        return result
    if baseline.summary.files or baseline.summary.patch_truncated or tested.summary.patch_truncated:
        result.error = "Baseline is not clean or checkpoint patch was truncated."
        return result
    try:
        ancestry = run_git(
            tested.repository_root,
            ["merge-base", "--is-ancestor", baseline.head_sha, tested.head_sha],
            limit=4096,
        )
        if (ancestry.returncode != 0 or ancestry.incomplete or ancestry.timed_out
                or ancestry.truncated):
            result.error = "Baseline commit is not proven to precede the tested HEAD."
            return result
        captured = run_git(
            tested.repository_root,
            ["-c", "color.diff=false", "-c", "diff.interHunkContext=0",
             "-c", "core.quotePath=false", "diff",
             "--no-color", "--no-ext-diff", "--no-textconv", "--find-renames",
             "--inter-hunk-context=0", "--no-relative", "--src-prefix=a/",
             "--dst-prefix=b/", "--unified=0", baseline.head_sha, "--"],
            limit=limit,
        )
    except (AppError, OSError, RuntimeError, ValueError) as exc:
        result.error = f"Diff collection failed: {type(exc).__name__}."
        return result
    if captured.truncated or captured.incomplete or captured.timed_out or captured.returncode != 0:
        result.error = "Diff was truncated or failed."
        return result
    try:
        patch = captured.stdout.decode("utf-8")
    except UnicodeError:
        result.error = "Diff path or content is not UTF-8."
        return result
    _parse_patch(patch, result, Path(tested.repository_root))
    if result.error:
        return result
    try:
        # Deliberately omit --exclude-standard: .git/info/exclude and the user's
        # core.excludesFile are writable outside the committed project rules.
        other = run_git(tested.repository_root,
                        ["ls-files", "--others", "-z",
                         "--exclude-per-directory=.gitignore", "--"], limit=limit)
        if other.returncode or other.incomplete or other.timed_out or other.truncated:
            raise ValueError("Untracked-file enumeration failed")
        paths = [part.decode("utf-8") for part in other.stdout.split(b"\0") if part]
    except (AppError, OSError, RuntimeError, UnicodeError, ValueError):
        result.error = "Untracked-file enumeration failed."
        return result
    for path in paths:
        path = path.replace("\\", "/")
        if path in result.lines or path in result.excluded:
            continue
        classification = _classification(path, Path(tested.repository_root))
        if classification:
            result.excluded[path] = classification
            continue
        target = Path(tested.repository_root) / path
        try:
            if target.is_symlink() or not target.is_file() or target.stat().st_size > limit:
                raise ValueError("untracked file is unavailable or oversized")
            content = target.read_bytes()
            content.decode("utf-8")
        except (OSError, UnicodeError, ValueError):
            result.error = f"Untracked source cannot be mapped: {path}."
            return result
        result.lines[path] = set(range(1, len(content.splitlines()) + 1))
    return result
